// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using cp_csharp.Data;

#nullable disable

namespace cp_csharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250907200457_dadostabelas")]
    partial class dadostabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cp_csharp.Fornecedor.RM98436_FornecedorModel", b =>
                {
                    b.Property<int>("idFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFornecedor"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("dsEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nrCEP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idFornecedor");

                    b.ToTable("RM98436_Fornecedores");
                });

            modelBuilder.Entity("cp_csharp.Pedido.RM98436_PedidoModel", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPedido"));

                    b.Property<DateTime>("dataPedido")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("valorTotal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("idPedido");

                    b.ToTable("RM98436_Pedidos");
                });

            modelBuilder.Entity("cp_csharp.Produto.RM98436_ProdutoModel", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<string>("nmProduto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("preco")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("idProduto");

                    b.ToTable("RM98436_Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
